{
	"id": "CVE-2017-12852",
	"repositories": [
		{
			"allow_forking": true,
			"created_at": "2017-09-30T05:21:48Z",
			"description": "test the CVE-2017-12852 in numpy v1.13.1 and v1.13.3 has fixed the bug ",
			"forks": 2,
			"forks_count": 2,
			"full_name": "BT123/numpy-1.13.1",
			"html_url": "https://github.com/BT123/numpy-1.13.1",
			"id": 105343958,
			"name": "numpy-1.13.1",
			"owner": {
				"avatar_url": "https://avatars.githubusercontent.com/u/9165608?v=4",
				"html_url": "https://github.com/BT123",
				"id": 9165608,
				"login": "BT123"
			},
			"pushed_at": "2017-10-20T03:34:01Z",
			"updated_at": "2017-11-03T06:18:22Z",
			"visibility": "public"
		}
	]
}
